---
- hosts: all
  sudo: true
  tasks:
#  - name: update yum
#    yum: name=* state=latest update_cache=yes 
  - name: install the galera rpm from a remote repo
    yum: name=http://www.percona.com/downloads/percona-release/percona-release-0.0-1.x86_64.rpm state=present
  - name: install socat from ext repo
    yum: name=http://pkgs.repoforge.org/socat/socat-1.7.1.3-1.el6.rf.x86_64.rpm state=present
  - name: install tcpwrappers
    yum: name=ftp://195.220.108.108/linux/centos/6.6/os/x86_64/Packages/tcp_wrappers-7.6-57.el6.x86_64.rpm state=present
  - name: install required packages
    yum: name={{ item }} state=present
    with_items:
    - Percona-XtraDB-Cluster-server
    - sysstat
    - wget
  - include: tasks/galera.yml
  - include: tasks/galera_perms.yml
